CREATE TABLE "v34_benchmark_scores" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_id" text NOT NULL,
	"round_id" text,
	"pnl_percent" real,
	"sharpe_ratio" real,
	"max_drawdown" real,
	"coherence" real,
	"reasoning_depth" real,
	"source_quality" real,
	"logical_consistency" real,
	"reasoning_integrity" real,
	"reasoning_transparency" real,
	"reasoning_grounding" real,
	"causal_reasoning" real,
	"epistemic_humility" real,
	"reasoning_traceability" real,
	"adversarial_coherence" real,
	"hallucination_rate" real,
	"instruction_discipline" real,
	"risk_awareness" real,
	"strategy_consistency" real,
	"adaptability" real,
	"confidence_calibration" real,
	"cross_round_learning" real,
	"outcome_accuracy" real,
	"market_regime_awareness" real,
	"edge_consistency" real,
	"trade_accountability" real,
	"reasoning_quality_index" real,
	"decision_accountability" real,
	"consensus_quality" real,
	"composite_score" real,
	"tier" text,
	"trade_count" integer,
	"scored_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v34_leaderboard" (
	"agent_id" text PRIMARY KEY NOT NULL,
	"agent_name" text NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"composite_score" real NOT NULL,
	"tier" text NOT NULL,
	"trade_count" integer DEFAULT 0,
	"rounds_played" integer DEFAULT 0,
	"dimension_scores" jsonb,
	"last_updated" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v34_research_exports" (
	"id" text PRIMARY KEY NOT NULL,
	"export_type" text NOT NULL,
	"agent_id" text,
	"round_id" text,
	"data" jsonb,
	"dimension_count" integer DEFAULT 28,
	"version" text DEFAULT '34.0',
	"exported_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v34_trade_grades" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_id" text NOT NULL,
	"round_id" text,
	"symbol" text NOT NULL,
	"action" text NOT NULL,
	"reasoning" text NOT NULL,
	"confidence" real NOT NULL,
	"coherence_score" real,
	"hallucination_flags" jsonb,
	"discipline_passed" text DEFAULT 'true',
	"reasoning_depth_score" real,
	"source_quality_score" real,
	"logical_consistency_score" real,
	"integrity_hash" text,
	"transparency_score" real,
	"accountability_score" real,
	"grounding_score" real,
	"consensus_quality_score" real,
	"causal_reasoning_score" real,
	"epistemic_humility_score" real,
	"reasoning_traceability_score" real,
	"adversarial_coherence_score" real,
	"predicted_outcome" text,
	"actual_outcome" text,
	"outcome_resolved" text DEFAULT 'pending',
	"overall_grade" text NOT NULL,
	"graded_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v35_benchmark_scores" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_id" text NOT NULL,
	"round_id" text,
	"pnl_percent" real,
	"sharpe_ratio" real,
	"max_drawdown" real,
	"coherence" real,
	"reasoning_depth" real,
	"source_quality" real,
	"logical_consistency" real,
	"reasoning_integrity" real,
	"reasoning_transparency" real,
	"reasoning_grounding" real,
	"causal_reasoning" real,
	"epistemic_humility" real,
	"reasoning_traceability" real,
	"adversarial_coherence" real,
	"information_asymmetry" real,
	"temporal_reasoning_quality" real,
	"hallucination_rate" real,
	"instruction_discipline" real,
	"risk_awareness" real,
	"strategy_consistency" real,
	"adaptability" real,
	"confidence_calibration" real,
	"cross_round_learning" real,
	"outcome_accuracy" real,
	"market_regime_awareness" real,
	"edge_consistency" real,
	"trade_accountability" real,
	"reasoning_quality_index" real,
	"decision_accountability" real,
	"consensus_quality" real,
	"composite_score" real,
	"tier" text,
	"trade_count" integer,
	"scored_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v35_leaderboard" (
	"agent_id" text PRIMARY KEY NOT NULL,
	"agent_name" text NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"composite_score" real NOT NULL,
	"tier" text NOT NULL,
	"trade_count" integer DEFAULT 0,
	"rounds_played" integer DEFAULT 0,
	"dimension_scores" jsonb,
	"last_updated" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v35_research_exports" (
	"id" text PRIMARY KEY NOT NULL,
	"export_type" text NOT NULL,
	"agent_id" text,
	"round_id" text,
	"data" jsonb,
	"dimension_count" integer DEFAULT 30,
	"version" text DEFAULT '35.0',
	"exported_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v35_trade_grades" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_id" text NOT NULL,
	"round_id" text,
	"symbol" text NOT NULL,
	"action" text NOT NULL,
	"reasoning" text NOT NULL,
	"confidence" real NOT NULL,
	"coherence_score" real,
	"hallucination_flags" jsonb,
	"discipline_passed" text DEFAULT 'true',
	"reasoning_depth_score" real,
	"source_quality_score" real,
	"logical_consistency_score" real,
	"integrity_hash" text,
	"transparency_score" real,
	"accountability_score" real,
	"grounding_score" real,
	"consensus_quality_score" real,
	"causal_reasoning_score" real,
	"epistemic_humility_score" real,
	"reasoning_traceability_score" real,
	"adversarial_coherence_score" real,
	"information_asymmetry_score" real,
	"temporal_reasoning_score" real,
	"predicted_outcome" text,
	"actual_outcome" text,
	"outcome_resolved" text DEFAULT 'pending',
	"overall_grade" text NOT NULL,
	"graded_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v36_benchmark_scores" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_id" text NOT NULL,
	"round_id" text,
	"pnl_percent" real,
	"sharpe_ratio" real,
	"max_drawdown" real,
	"coherence" real,
	"reasoning_depth" real,
	"source_quality" real,
	"logical_consistency" real,
	"reasoning_integrity" real,
	"reasoning_transparency" real,
	"reasoning_grounding" real,
	"causal_reasoning" real,
	"epistemic_humility" real,
	"reasoning_traceability" real,
	"adversarial_coherence" real,
	"information_asymmetry" real,
	"temporal_reasoning_quality" real,
	"market_microstructure_quality" real,
	"conviction_consistency" real,
	"hallucination_rate" real,
	"instruction_discipline" real,
	"risk_awareness" real,
	"strategy_consistency" real,
	"adaptability" real,
	"confidence_calibration" real,
	"cross_round_learning" real,
	"outcome_accuracy" real,
	"market_regime_awareness" real,
	"edge_consistency" real,
	"trade_accountability" real,
	"reasoning_quality_index" real,
	"decision_accountability" real,
	"consensus_quality" real,
	"composite_score" real,
	"tier" text,
	"trade_count" integer,
	"scored_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v36_leaderboard" (
	"agent_id" text PRIMARY KEY NOT NULL,
	"agent_name" text NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"composite_score" real NOT NULL,
	"tier" text NOT NULL,
	"trade_count" integer DEFAULT 0,
	"rounds_played" integer DEFAULT 0,
	"dimension_scores" jsonb,
	"last_updated" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v36_research_exports" (
	"id" text PRIMARY KEY NOT NULL,
	"export_type" text NOT NULL,
	"agent_id" text,
	"round_id" text,
	"data" jsonb,
	"dimension_count" integer DEFAULT 32,
	"version" text DEFAULT '36.0',
	"exported_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v36_trade_grades" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_id" text NOT NULL,
	"round_id" text,
	"symbol" text NOT NULL,
	"action" text NOT NULL,
	"reasoning" text NOT NULL,
	"confidence" real NOT NULL,
	"coherence_score" real,
	"hallucination_flags" jsonb,
	"discipline_passed" text DEFAULT 'true',
	"reasoning_depth_score" real,
	"source_quality_score" real,
	"logical_consistency_score" real,
	"integrity_hash" text,
	"transparency_score" real,
	"accountability_score" real,
	"grounding_score" real,
	"consensus_quality_score" real,
	"causal_reasoning_score" real,
	"epistemic_humility_score" real,
	"reasoning_traceability_score" real,
	"adversarial_coherence_score" real,
	"information_asymmetry_score" real,
	"temporal_reasoning_score" real,
	"market_microstructure_score" real,
	"conviction_consistency_score" real,
	"predicted_outcome" text,
	"actual_outcome" text,
	"outcome_resolved" text DEFAULT 'pending',
	"overall_grade" text NOT NULL,
	"graded_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v37_benchmark_scores" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_id" text NOT NULL,
	"round_id" text,
	"pnl_percent" real,
	"sharpe_ratio" real,
	"max_drawdown" real,
	"coherence" real,
	"reasoning_depth" real,
	"source_quality" real,
	"logical_consistency" real,
	"reasoning_integrity" real,
	"reasoning_transparency" real,
	"reasoning_grounding" real,
	"causal_reasoning" real,
	"epistemic_humility" real,
	"reasoning_traceability" real,
	"adversarial_coherence" real,
	"information_asymmetry" real,
	"temporal_reasoning_quality" real,
	"reasoning_auditability" real,
	"decision_reversibility" real,
	"reasoning_composability" real,
	"strategic_foresight" real,
	"hallucination_rate" real,
	"instruction_discipline" real,
	"risk_awareness" real,
	"strategy_consistency" real,
	"adaptability" real,
	"confidence_calibration" real,
	"cross_round_learning" real,
	"outcome_accuracy" real,
	"market_regime_awareness" real,
	"edge_consistency" real,
	"trade_accountability" real,
	"reasoning_quality_index" real,
	"decision_accountability" real,
	"consensus_quality" real,
	"composite_score" real,
	"tier" text,
	"trade_count" integer,
	"scored_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v37_leaderboard" (
	"agent_id" text PRIMARY KEY NOT NULL,
	"agent_name" text NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"composite_score" real NOT NULL,
	"tier" text NOT NULL,
	"trade_count" integer DEFAULT 0,
	"rounds_played" integer DEFAULT 0,
	"dimension_scores" jsonb,
	"last_updated" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v37_research_exports" (
	"id" text PRIMARY KEY NOT NULL,
	"export_type" text NOT NULL,
	"agent_id" text,
	"round_id" text,
	"data" jsonb,
	"dimension_count" integer DEFAULT 34,
	"version" text DEFAULT '37.0',
	"exported_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "v37_trade_grades" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_id" text NOT NULL,
	"round_id" text,
	"symbol" text NOT NULL,
	"action" text NOT NULL,
	"reasoning" text NOT NULL,
	"confidence" real NOT NULL,
	"coherence_score" real,
	"hallucination_flags" jsonb,
	"discipline_passed" text DEFAULT 'true',
	"reasoning_depth_score" real,
	"source_quality_score" real,
	"logical_consistency_score" real,
	"integrity_hash" text,
	"transparency_score" real,
	"accountability_score" real,
	"grounding_score" real,
	"consensus_quality_score" real,
	"causal_reasoning_score" real,
	"epistemic_humility_score" real,
	"reasoning_traceability_score" real,
	"adversarial_coherence_score" real,
	"information_asymmetry_score" real,
	"temporal_reasoning_score" real,
	"reasoning_auditability_score" real,
	"decision_reversibility_score" real,
	"reasoning_composability_score" real,
	"strategic_foresight_score" real,
	"predicted_outcome" text,
	"actual_outcome" text,
	"outcome_resolved" text DEFAULT 'pending',
	"overall_grade" text NOT NULL,
	"graded_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "v34_benchmark_scores" ADD CONSTRAINT "v34_benchmark_scores_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v34_leaderboard" ADD CONSTRAINT "v34_leaderboard_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v34_trade_grades" ADD CONSTRAINT "v34_trade_grades_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v35_benchmark_scores" ADD CONSTRAINT "v35_benchmark_scores_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v35_leaderboard" ADD CONSTRAINT "v35_leaderboard_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v35_trade_grades" ADD CONSTRAINT "v35_trade_grades_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v36_benchmark_scores" ADD CONSTRAINT "v36_benchmark_scores_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v36_leaderboard" ADD CONSTRAINT "v36_leaderboard_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v36_trade_grades" ADD CONSTRAINT "v36_trade_grades_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v37_benchmark_scores" ADD CONSTRAINT "v37_benchmark_scores_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v37_leaderboard" ADD CONSTRAINT "v37_leaderboard_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v37_trade_grades" ADD CONSTRAINT "v37_trade_grades_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;